name: Release Workflow
on:
  pull_request:
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: echo Branch
        run: |
          echo $(git rev-parse --abbrev-ref HEAD)
          echo $(git branch --show-current)
          ls -artl      
      - name: Run Script
        run: sudo ./.github/scripts/hello.sh
      
      - name: Run Script
        run: sudo ./.github/scripts/test.sh

  
